config/routes.rb
Rails.application.routes.draw do
  resources :salons
  resources :annonceurs

devise_for :users, skip: [:registrations]
as :user do
  get 'B21zukt938lama272kutoni', to: 'devise/registrations#new', as: :new_user_registration
  post 'B21zukt938lama272kutoni', to: 'devise/registrations#create', as: :user_registration
end






#  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmations: "users/confirmations", passwords: "users/passwords" }, :skip => [:sessions]
# devise_scope :user do
#     get "/sign_in" => "devise/sessions#new", as: "new_user_session" # custom path to login/sign_in
#     post "/sign_in" => "devise/sessions#create", as: "user_session" # custom path to login/sign_in
#     match "/sign_out" => "devise/sessions#destroy", as: "destroy_user_session", :via => Devise.mappings[:user].sign_out_via
#     get "/B21zukt938lama272kutoni" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
#     post "/B21zukt938lama272kutoni" => "devise/registrations#create", as: "user_registration" # custom path to login/sign_in
#   end

  # Below for all other routes:


  get "/pages/:page" => "pages#show"



  root to: 'annonceurs#new'

    resources :prospects, only: [:create, :index, :destroy, :edit]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/annonceur.rb
class Annonceur < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prospect.rb
class Prospect < ApplicationRecord
end

app/models/salon.rb
class Salon < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/annonceurs_controller.rb
class AnnonceursController < ApplicationController
  before_action :set_annonceur, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:home, :new, :create, :show]
  # GET /annonceurs
  # GET /annonceurs.json
  def index
    @annonceurs = Annonceur.all
  end

  # GET /annonceurs/1
  # GET /annonceurs/1.json
  def show
  end

  # GET /annonceurs/new
  def new
    @annonceur = Annonceur.new
  end

  # GET /annonceurs/1/edit
  def edit
  end

  # POST /annonceurs
  # POST /annonceurs.json
  def create
    @annonceur = Annonceur.new(annonceur_params)


      if @annonceur.save
        redirect_to "/pages/thanks"

      else
       render :new

      end

  end

  # PATCH/PUT /annonceurs/1
  # PATCH/PUT /annonceurs/1.json
  def update
    respond_to do |format|
      if @annonceur.update(annonceur_params)
        format.html { redirect_to @annonceur, notice: 'annonceur was successfully updated.' }
        format.json { render :show, status: :ok, location: @annonceur }
      else
        format.html { render :edit }
        format.json { render json: @annonceur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annonceurs/1
  # DELETE /annonceurs/1.json
  def destroy
    @annonceur.destroy
    respond_to do |format|
      format.html { redirect_to annonceurs_url, notice: 'annonceur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annonceur
      @annonceur = Annonceur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonceur_params
      params.require(:annonceur).permit(:first_name, :last_address, :mail, :company, :job_title, :phone, :last_name, :message)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

 def show
      render template: "pages/#{params[:page]}"

end

  def home
  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :set_salon, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:home, :new, :create, :show]

  # GET /salons
  # GET /salons.json
  def index
    @salons = Salon.all
  end

  # GET /salons/1
  # GET /salons/1.json
  def show
  end

  # GET /salons/new
  def new
    @salon = Salon.new
  end

  # GET /salons/1/edit
  def edit
  end

  # POST /salons
  # POST /salons.json
  def create
    @salon = Salon.new(salon_params)
      if @salon.save
        redirect_to "/pages/thanks"
      else
        render :new
    end
  end

  # PATCH/PUT /salons/1
  # PATCH/PUT /salons/1.json
  def update
    respond_to do |format|
      if @salon.update(salon_params)
        format.html { redirect_to @salon, notice: 'Salon was successfully updated.' }
        format.json { render :show, status: :ok, location: @salon }
      else
        format.html { render :edit }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salons/1
  # DELETE /salons/1.json
  def destroy
    @salon.destroy
    respond_to do |format|
      format.html { redirect_to salons_url, notice: 'Salon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon
      @salon = Salon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salon_params
      params.require(:salon).permit(:first_name,:message, :last_name, :salon, :phone, :email, :adress, :postal_code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/annonceurs/_form.html.erb
<div class="backgroundlanding" style="background-image: url('<%= image_path 'today-pink-is-my-mood.jpg' %>');">
  <div class="logo">

 <%= image_tag 'logo.png', class: 'logo-img', alt: "Logo Eliana Media" %>

  </div>


  <div class="col-sm-8">
    <div class="banner">
    <div class="banner-content">
      <h1>Le rendez-vous entre votre marque et les femmes</h1>
      <h2>Eliana Media propose des solutions divertissements et des opportunités marketing dans des salons de beautés à Paris</h2>



    </div>
  </div>

  </div>




  <div class="col-sm-4">
    <div class="boxform">
      <div class="column-form">
        <%= simple_form_for(@annonceur) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs" style="margin-top: 15px;">
            <div class="col-xs-6">
              <%= f.input :first_name, label: false,  placeholder: "Prénom",   required: true %>
              <%= f.input :company, label: 'Entreprise',label: false,  placeholder: "Entreprise", required: true  %>

            </div>
            <div class="col-xs-6">
              <%= f.input :last_name, label: 'Nom',label: false,  placeholder: "Nom",  required: true  %>
              <%= f.input :job_title, label: 'Poste',label: false,  placeholder: 'Poste' , required: true %>
            </div>
            <div class="col-xs-12">
              <%= f.input :mail, label: 'Adresse email',label: false, placeholder: 'Email' , required: true  %>
              <%= f.input :phone, label: 'Téléphone',label: false, placeholder: 'Téléphone', required: true  %>
                <%= f.input :message, label: 'frfgtr',label: false, placeholder: 'Votre message (facultatif)', required: false  %>
            </div>

          </div>

          <div class="form-actions btn-treehouse">
            <center><%= f.submit "Envoyer", class: "btn btn-primary" %></center>
          </div>
          <div class="rgpd">
            <p>En fournissant votre adresse e-mail, (ou vos données personnelles ci-dessus) vous consentez expressément à leur stockage dans notre base de données pour en faire usage afin de vous envoyer des messages à des fins commerciales, marketing ou pour vous notifier d’importants changements apportés à nos services. Vous pouvez vous désabonner ou modifier votre adresse e-mail à tout moment en suivant les instructions mentionnées dans chaque communication par e-mail ou en envoyant un e-mail à privacy@evamedia.com</p>
        </div>
        <% end %>
      </div>
    </div>

</div>

<div class="footer scroll">

    <a href="#usp">
    <i class="fa fa-long-arrow-down" aria-hidden="true"></i>
  </a>

  </div>
</div>

<center>
<div class="container" >
  <div class="col-xs-12 text-xs-center" >
    <h3 class="text-thin" >Pourquoi annoncer dans nos salons?</h3><br></br>
  </div>
  <div class="row" >
    <div class="col-xs-12" >
      <div class="row justify-center justify-start-lg text-xs-center" >
        <div class="col-md-4" style="list-style:none;" >
          <img src="<%= image_path 'tele.png' %>" alt="Campagne DOOH pour femmes" style="width: 50px;" >
          <h4 >Une mémorisation record</h4>
          <p >45 minutes de relaxation, sans distraction  propice à la mediation de votre message</p>
        </div>
        <div class="col-md-4" style="list-style:none;">
          <img src="<%= image_path 'market.png' %>" alt="Affichage publicitaire Out-Of-Home" style="width: 50px;" d>
          <h4 >Maximiser votre ROI</h4>
          <p >Un CPM attractif, zéro frais de mise en service et un suivi de vos performances en temps réel.</p>
        </div>
        <div class="col-md-4" style="list-style:none;" >
          <img src="<%= image_path 'partnership1.png' %>" alt="Régie publicitaire DOOH" style="width: 50px;" >
          <h4 >Un partenaire à votre écoute</h4>
          <p >Plus qu'un simple fournisseur d'espace média, nous vous accompagnons dans l'integration dans notre réseau.</p>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="grille"> 
  <div class="row nopadding"> 
    <div class="col-xs-6 nopadding" style="min-height: 70vh;width: 50vw; background-image:  url('https://images.unsplash.com/photo-1502323777036-f29e3972d82f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=762ab46fb81f4b88e628a11024a32330&auto=format&fit=crop&w=1350&q=80');background-position: center;"></div>
    <div class="col-xs-6 nopadding">    <h3>Fini les clients qui s'ennuient </h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.</p></div>

  </div>
</div>

<div class="grille"> 
  <div class="row nopadding"> 
    <div class="col-xs-6 nopadding">
    <div class="banner-content nopadding">
      <h3 >Fini les clients qui s'ennuient </h3>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.  </p>



  </div> 
</div>
    <div class="col-xs-6 nopadding" style="min-height: 70vh;width: 50vw; background-image:  url('https://images.unsplash.com/photo-1457972729786-0411a3b2b626?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=516d4a371891ea27ba0e8943af3a98d2&auto=format&fit=crop&w=1350&q=80');background-position: center;"></div>

  </div>
</div>
<div class="cta"> 
  <h3>Vous avez des questions?</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. </p>
  <a href="#" class="btn-medium">Nous écrire</a>



</div>
</center>
</center>
<br></br>
      <div class="footer">
  <div class="footer-links" id="usp">
    <a href="#">Cgv</a>
      <%= link_to 'Salon', new_salon_path %>
  </div>
  <div class="footer-copyright">
    © 2018 Eliana Media
  </div>
</div>

app/views/annonceurs/edit.html.erb
<h1>Editing annonceur</h1>

<%= render 'form', annonceur: @annonceur %>

<%= link_to 'Show', @annonceur %> |
<%= link_to 'Back', annonceurs_path %>

app/views/annonceurs/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<center>
  <h1>Tableau de bord</h1>

  <table>
    <thead>
      <tr>
        <th>Prénom</th>
        <th>Nom</th>
        <th>Email</th>
        <th>Entreprise</th>
        <th>Poste</th>
        <th>Téléphone</th>
        <th>Message</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @annonceurs.each do |annonceur| %>
        <tr>
          <td><% if annonceur.present? %><%= annonceur.first_name %> <% else %> <% end %></td>
          <td><% if annonceur.present? %><%= annonceur.last_name %> <% else %> <% end %></td>
          <td><% if annonceur.present? %><%= annonceur.mail %> <% else %> <% end %></td>
          <td><% if annonceur.present? %><%= annonceur.company %> <% else %> <% end %></td>
          <td><% if annonceur.present? %><%= annonceur.job_title %> <% else %> <% end %></td>
          <td><% if annonceur.present? %><%= annonceur.phone %> <% else %> <% end %></td>
          <td><%= link_to 'Edit', edit_annonceur_path(annonceur) %></td>
          <td><%= link_to 'Destroy', annonceur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><% if annonceur.present? %><%= annonceur.message %> <% else %> <% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</center>

app/views/annonceurs/new.html.erb
<%= render 'form', annonceur: @annonceur %>

app/views/annonceurs/show.html.erb
<div class="backgroundlanding" style="background-image: url('<%= image_path 'today-pink-is-my-mood.jpg' %>');">
  <div class="logo">

      <%= image_tag 'logo.png'%>


  </div>
  <br/>

<div style="width: 40vw; margin:auto;">
  <div class="boxform column-form">
    <h2>
Merci <%= @annonceur.first_name %> !
    </h2>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Eliana Media - Le rendez-vous entre votre marque et les femmes</title>
    <meta name="description" content="La régie DOOH Eliana Media propose des solutions divertissements et des opportunités d'affichage publicitaire dans des salons de beautés à Paris. Atteindre des femmes en Digital Out-Of-Home n'a jamais été aussi simple." />
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121429772-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121429772-1');
</script>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.png' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/show.html.erb
<div class="backgroundlanding" style="background-image: url('#');">


<div style="width: 60vw; margin:auto; padding:20px; color: #f4f4f4;">
  <div class="boxform " style=" padding:20px;">
<center>

  <h1 style="color:#17bebb; font-size: 82px;"><i class="fa fa-check-circle "></i></h1>
<h3>Félicitations !
</h3>
<br/>
<p>Nous vous êtes bien enregistré pour notre offre de lancement! Nous vous avons envoyé un email de bienvenue - nous vous remercions pour la confirmation ! Bientôt vous allez bientôt recevoir notre offre de lancement!</p>

<br/>
<p>A très bientôt,</p>
<p>Votre Equipe ELIANA Media.</p>

<%= image_tag 'logo.png', width: "200px" %>
<p>hello@elianamedia.com</p>
<br/>
</center>
  </div>
</div>

app/views/pages/thanks.html.erb
<div class="backgroundlanding" style="background-image: url('#');">


<div style="width: 60vw; margin:auto; padding:20px; color: #f4f4f4;">
  <div class="boxform " style=" padding:20px;">
<center>

  <h1 style="color:#17bebb; font-size: 82px;"><i class="fa fa-check-circle "></i></h1>
<h3>Félicitations !
</h3>
<br/>
<p>Nous vous êtes bien enregistré pour notre offre de lancement! Nous vous avons envoyé un email de bienvenue - nous vous remercions pour la confirmation ! Bientôt vous allez bientôt recevoir notre offre de lancement!</p>

<br/>
<p>A très bientôt,</p>
<p>Votre Equipe ELIANA Media.</p>

<%= image_tag 'logo.png', width: "200px" %>
<p>hello@elianamedia.com</p>
<br/>
</center>
  </div>
</div>

app/views/prospectts/_form.html.erb
<div class="backgroundlanding" style="background-image: url('<%= image_path 'today-pink-is-my-mood.jpg' %>');">
  <div class="logo">

 <%= image_tag 'logo.png', style: 'width: 250px;' %>

  </div>


  <div class="col-sm-8">
    <div class="banner">
    <div class="banner-content">
      <h2>Le rendez-vous entre votre marque et les femmes</h2>
      <h4>Eliana Media propose des solutions divertissements et des opportunités marketing dans des salons de beautés à Paris</h4>



    </div>
  </div>

  </div>




  <div class="col-sm-4">
    <div class="boxform">
      <div class="column-form">
        <%= simple_form_for(@prospectt) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs" style="margin-top: 15px;">
            <div class="col-xs-6">
              <%= f.input :first_name, label: false,  placeholder: "Prénom",   required: true %>
              <%= f.input :company, label: 'Entreprise',label: false,  placeholder: "Entreprise", required: true  %>

            </div>
            <div class="col-xs-6">
              <%= f.input :last_name, label: 'Nom',label: false,  placeholder: "Nom",  required: true  %>
              <%= f.input :job_title, label: 'Poste',label: false,  placeholder: 'Poste' , required: true %>
            </div>
            <div class="col-xs-12">
              <%= f.input :mail, label: 'Adresse email',label: false, placeholder: 'Email' , required: true  %>
              <%= f.input :phone, label: 'Téléphone',label: false, placeholder: 'Téléphone', required: true  %>
                <%= f.input :message, label: 'frfgtr',label: false, placeholder: 'Votre message (facultatif)', required: false  %>
            </div>

          </div>

          <div class="form-actions btn-treehouse">
            <center><%= f.submit "Envoyer", class: "btn btn-primary" %></center>
          </div>
          <div class="rgpd">
            <p>En fournissant votre adresse e-mail, (ou vos données personnelles ci-dessus) vous consentez expressément à leur stockage dans notre base de données pour en faire usage afin de vous envoyer des messages à des fins commerciales, marketing ou pour vous notifier d’importants changements apportés à nos services. Vous pouvez vous désabonner ou modifier votre adresse e-mail à tout moment en suivant les instructions mentionnées dans chaque communication par e-mail ou en envoyant un e-mail à privacy@evamedia.com</p>
        </div>
        <% end %>
      </div>
    </div>

</div>

<div class="footer scroll">

    <a href="#usp">
    <i class="fa fa-long-arrow-down" aria-hidden="true"></i>
  </a>

  </div>
</div>

<center>
<div class="container" >
  <div class="col-xs-12 text-xs-center" >
    <h3 class="text-thin" >Pourquoi annoncer dans nos salons?</h3><br></br>
  </div>
  <div class="row" >
    <div class="col-xs-12" >
      <ul class="row justify-center justify-start-lg text-xs-center" >
        <li class="col-md-4" style="list-style:none;" >
          <img src="<%= image_path 'television.png' %>" alt="Publicités pour femmes" style="width: 50px;" >
          <h4 >Une mémorisation record</h4>
          <p >45 minutes de relaxation, sans distraction  propice à la mediation de votre message</p>
        </li>
        <li class="col-md-4" style="list-style:none;">
          <img src="<%= image_path 'growth.png' %>" alt="Espace média rentable" style="width: 50px;" d>
          <h4 >Maximiser votre ROI</h4>
          <p >Un CPM attractif, zéro frais de mise en service et un suivi de vos performances en temps réel.</p>
        </li>
        <li class="col-md-4" style="list-style:none;" >
          <img src="<%= image_path 'hand-shake.png' %>" alt="" style="width: 50px;" >
          <h4 >Un partenaire à votre écoute</h4>
          <p >Plus qu'un simple fournisseur d'espace média, nous vous accompagnons dans l'integration dans notre réseau.</p>
        </li>
      </ul>
    </div>
  </div>
</div>
</center>
<br></br>
      <div class="footer">
  <div class="footer-links" id="usp">
    <a href="#">Cgv</a>
      <%= link_to 'Salon', new_salon_path %>
  </div>
  <div class="footer-copyright">
    © 2018 Eva Media
  </div>
</div>

app/views/prospectts/show.html.erb
<div class="backgroundlanding" style="background-image: url('<%= image_path 'today-pink-is-my-mood.jpg' %>');">
  <div class="logo">

      <%= image_tag 'logo.png'%>


  </div>
  <br/>

<div style="width: 40vw; margin:auto;">
  <div class="boxform column-form">
    <h2>
Merci <%= @prospectt.first_name %> !
    </h2>

  </div>
</div>

app/views/salons/_form.html.erb
<div class="backgroundlanding" style="background-image: url('<%= image_path 'today-pink-is-my-mood.jpg' %>');">
  <div class="logo">

      <%= image_tag 'logo.png', class: 'logo-img', alt: "Logo Eliana Media" %>


  </div>


  <div class="col-sm-8">
    <div class="banner">
    <div class="banner-content">
      <h1>Fini les clients qui s'ennuient </h1>
      <h2>Divertissez votre clientèle en gagnant de l'argent</h2>



    </div>
  </div>

  </div>




  <div class="col-sm-4">
    <div class="boxform">
      <div class="column-form">
        <%= simple_form_for(@salon) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs" style="margin-top: 15px;">
            <div class="col-xs-6">
              <%= f.input :first_name, label: false,  placeholder: "Prénom",   required: true %>
              <%= f.input :adress, label: 'Entreprise',label: false,  placeholder: "Adresse", required: true  %>

            </div>
            <div class="col-xs-6">
              <%= f.input :last_name, label: 'Nom',label: false,  placeholder: "Nom",  required: true  %>
              <%= f.input :postal_code, label: 'Poste',label: false,  placeholder: 'Code Postal' , required: true %>
            </div>
            <div class="col-xs-12">
              <%= f.input :email, label: 'Téléphone',label: false, placeholder: 'e-mail', required: true  %>
              <%= f.input :salon, label: 'Adresse email',label: false, placeholder: 'Salon' , required: true  %>
              <%= f.input :phone, label: 'Téléphone',label: false, placeholder: 'Téléphone', required: true  %>
              <%= f.input :message, label: 'frfgtr',label: false, placeholder: 'Votre message (facultatif)', required: false  %>

            </div>

          </div>

          <div class="form-actions btn-treehouse">
            <center><%= f.submit "Envoyer", class: "btn btn-primary" %></center>
          </div>
          <div class="rgpd">
            <p>En fournissant votre adresse e-mail, (ou vos données personnelles ci-dessus) vous consentez expressément à leur stockage dans notre base de données pour en faire usage afin de vous envoyer des messages à des fins commerciales, marketing ou pour vous notifier d’importants changements apportés à nos services. Vous pouvez vous désabonner ou modifier votre adresse e-mail à tout moment en suivant les instructions mentionnées dans chaque communication par e-mail ou en envoyant un e-mail à privacy@evamedia.com</p>
        </div>
        <% end %>
      </div>
    </div>

</div>


</div>



<center>
<div class="container" >
  <div class="col-xs-12" ><br/><br/>
    <h3 class="text-thin" >Pourquoi Eliana?</h3><br></br>
  </div>
  <div class="row" >
    <div class="col-xs-12" >
      <div class="row" >
        <div class="col-md-4" style="list-style:none;" >
          <img src="<%= image_path 'tele.png' %>" alt="Campagne DOOH pour femmes" style="width: 50px;" >
          <h4 >Le bien être de vos clients avant tout</h4>
          <p>Une offre de divertissement amusante actualisée par des flux en temps réel</p>
        </div>
        <div class="col-md-4" style="list-style:none;">
          <img src="<%= image_path 'Time.png' %>" alt="Affichage publicitaire Out-Of-Home" style="width: 50px;" d>
          <h4 >C'est simple, et il y a rien à faire !</h4>
          <p >De l'installation à la maintenance, on s'occupe de tout ! Zéro souci.  </p>
        </div>
        <div class="col-md-4" style="list-style:none;" >
          <img src="<%= image_path 'cash.png' %>" alt="Régie publicitaire DOOH" style="width: 50px;" >
          <h4>Ca rapporte de l'argent !</h4>
          <p >Zéro frais. Nous vous apportons un rémunération supplémentaire avec notre loyer attractif.</p>
        </div>
      </div>
    </div>
  </div>
</div>


      
      <div class="footer">
  <div class="footer-links" id="usp">
    <a href="#">Cgv</a>
    <%= link_to 'Annonceur', new_annonceur_path %>
  </div>
  <div class="footer-copyright">
    © 2018 Eliana Media
  </div>
</div>

app/views/salons/edit.html.erb
<h1>Editing Salon</h1>

<%= render 'form', salon: @salon %>

<%= link_to 'Show', @salon %> |
<%= link_to 'Back', salons_path %>

app/views/salons/index.html.erb
<h1>Salons</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Salon</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Adress</th>
      <th>Postal code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salons.each do |salon| %>
      <tr>
        <td><%= salon.first_name %></td>
        <td><%= salon.last_name %></td>
        <td><%= salon.salon %></td>
        <td><%= salon.phone %></td>
        <td><%= salon.email %></td>
        <td><%= salon.adress %></td>
        <td><%= salon.postal_code %></td>
        <td><%= link_to 'Show', salon %></td>
        <td><%= link_to 'Edit', edit_salon_path(salon) %></td>
        <td><%= link_to 'Destroy', salon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/salons/new.html.erb
<%= render 'form', salon: @salon %>

app/views/salons/show.html.erb
<div class="backgroundlanding" style="background-image: url('<%= image_path 'girl-showing-an-ok-sign.jpg' %>');">
  <div class="logo">

      <%= image_tag 'logo.png'%>


  </div>
  <br/>

<div style="width: 40vw; margin:auto;">
  <div class="boxform column-form">
    <h2>
Merci <%= @salon.first_name %> !
    </h2>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>